import { Station } from "@/types/station";

export const fetchNearbyStations = async (): Promise<Station[]> => {
  return [
    {
      id: "hitech-city",
      name: "Hitech City",
      distance: "1.2 km",
      rating: 4.7,
      available: 5,
      total: 10,
      type: "DC Fast",
      price: 19,
      address: "HITEC City, Madhapur, Hyderabad, Telangana",
      onDemand: true,
      city: "Hyderabad",
      supportedVehicles: ["2W", "3W", "Car", "SUV"],
      markerX: 0.62,
      markerY: 0.34,
      lat: 17.4435,
      lng: 78.3772,
    },
    {
      id: "gachibowli",
      name: "Gachibowli",
      distance: "4.0 km",
      rating: 4.6,
      available: 2,
      total: 8,
      type: "AC Level 2",
      price: 14,
      address: "Gachibowli Financial District, Hyderabad, Telangana",
      onDemand: false,
      city: "Hyderabad",
      supportedVehicles: ["2W", "3W", "Car"],
      markerX: 0.48,
      markerY: 0.52,
      lat: 17.4401,
      lng: 78.3489,
    },
    {
      id: "banjara-hills",
      name: "Banjara Hills",
      distance: "6.5 km",
      rating: 4.8,
      available: 0,
      total: 6,
      type: "DC Fast",
      price: 20,
      address: "Banjara Hills, Hyderabad, Telangana",
      onDemand: true,
      city: "Hyderabad",
      supportedVehicles: ["Car", "SUV"],
      markerX: 0.38,
      markerY: 0.29,
      lat: 17.4126,
      lng: 78.4483,
    },
    {
      id: "charminar",
      name: "Charminar",
      distance: "9.1 km",
      rating: 4.5,
      available: 3,
      total: 5,
      type: "AC Level 2",
      price: 12,
      address: "Old City, Hyderabad, Telangana",
      onDemand: false,
      city: "Hyderabad",
      supportedVehicles: ["2W", "3W"],
      markerX: 0.22,
      markerY: 0.72,
      lat: 17.3616,
      lng: 78.4747,
    },
    {
      id: "shamshabad",
      name: "Shamshabad RGIA",
      distance: "21 km",
      rating: 4.4,
      available: 6,
      total: 12,
      type: "DC Fast",
      price: 22,
      address: "Rajiv Gandhi International Airport (RGIA), Shamshabad, Hyderabad",
      onDemand: true,
      city: "Hyderabad",
      supportedVehicles: ["Car", "SUV", "Truck", "Bus"],
      markerX: 0.12,
      markerY: 0.88,
      lat: 17.2403,
      lng: 78.4294,
    },
  ];
};